name = "Simplicity"
license = "MIT"
licenselink = "https://github.com/rowellx68/hugo-theme-simplicity/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/rowellx68/"
tags = []
features = []
min_version = "0.34"

[author]
  name = "Rowell Heria"
  homepage = "https://rowell.heria.uk"
